#!/usr/bin/env bash
set -euo pipefail

# This script is generated by the Gemini agent to run only the comparison part.

DATA_DIR="federated_data"
FED_RUN="runs/fedavg_batch/seed0"
BFL_RUN="runs/bfl_batch/run_20260108_034420"
SEED="0"
MC_EVAL="50"
HIER_BOOT="1000"

echo "[INFO] Running client-level comparison"

python scripts/eval_compare_clients.py \
  --data-dir "${DATA_DIR}" \
  --fedavg-runs "${FED_RUN}" \
  --bfl-runs "${BFL_RUN}" \
  --seeds "${SEED}" \
  --mc-eval "${MC_EVAL}" \
  --hier-bootstrap-n "${HIER_BOOT}" \
  --out-json "outputs/bfl_vs_fedavg_client_comparison.json" \
  --out-csv "outputs/bfl_vs_fedavg_client_comparison.csv"

echo "[DONE] Comparison finished."
